"""empty message

Revision ID: 6cc8994556aa
Revises: 
Create Date: 2018-03-21 14:47:44.688143

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6cc8994556aa'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email_verify_codes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=True),
    sa.Column('verifyCode', sa.String(length=10), nullable=True),
    sa.Column('createTime', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_email_verify_codes_email'), 'email_verify_codes', ['email'], unique=False)
    op.create_table('phone_verify_codes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('phoneNumber', sa.String(length=12), nullable=True),
    sa.Column('phoneVerifyCode', sa.String(length=10), nullable=True),
    sa.Column('createTime', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_phone_verify_codes_phoneNumber'), 'phone_verify_codes', ['phoneNumber'], unique=False)
    op.create_table('repair_problems',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('problem', sa.String(length=100), nullable=True),
    sa.Column('machineType', sa.String(length=30), nullable=True),
    sa.Column('systemType', sa.String(length=30), nullable=True),
    sa.Column('freeTime', sa.String(length=100), nullable=True),
    sa.Column('address', sa.String(length=150), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_repair_problems_id'), 'repair_problems', ['id'], unique=False)
    op.create_table('schools',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('schoolName', sa.String(length=50), nullable=True),
    sa.Column('schoolCode', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_schools_id'), 'schools', ['id'], unique=False)
    op.create_index(op.f('ix_schools_schoolCode'), 'schools', ['schoolCode'], unique=False)
    op.create_index(op.f('ix_schools_schoolName'), 'schools', ['schoolName'], unique=True)
    op.create_table('teams',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('teamName', sa.String(length=50), nullable=True),
    sa.Column('introdution', sa.Text(), nullable=True),
    sa.Column('peopleSum', sa.Integer(), nullable=True),
    sa.Column('teamCode', sa.String(length=40), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('teamCode'),
    sa.UniqueConstraint('teamName')
    )
    op.create_table('need_repair_mans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('phone', sa.String(length=12), nullable=True),
    sa.Column('name', sa.String(length=20), nullable=True),
    sa.Column('academy', sa.String(length=50), nullable=True),
    sa.Column('schoolId', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['schoolId'], ['schools.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_need_repair_mans_phone'), 'need_repair_mans', ['phone'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=50), nullable=True),
    sa.Column('passwordHash', sa.String(length=128), nullable=True),
    sa.Column('authority', sa.Integer(), nullable=True),
    sa.Column('teamId', sa.Integer(), nullable=True),
    sa.Column('schoolId', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['schoolId'], ['schools.id'], ),
    sa.ForeignKeyConstraint(['teamId'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=False)
    op.create_table('orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('orderNumber', sa.String(length=50), nullable=True),
    sa.Column('createTime', sa.DateTime(), nullable=True),
    sa.Column('takeTime', sa.DateTime(), nullable=True),
    sa.Column('finishedTime', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.Column('repairManId', sa.Integer(), nullable=True),
    sa.Column('engineerId', sa.Integer(), nullable=True),
    sa.Column('problemId', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['engineerId'], ['users.id'], ),
    sa.ForeignKeyConstraint(['problemId'], ['repair_problems.id'], ),
    sa.ForeignKeyConstraint(['repairManId'], ['need_repair_mans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_orders_orderNumber'), 'orders', ['orderNumber'], unique=True)
    op.create_table('team_leader',
    sa.Column('teamId', sa.Integer(), nullable=False),
    sa.Column('schoolId', sa.Integer(), nullable=True),
    sa.Column('teamLeaderId', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['schoolId'], ['schools.id'], ),
    sa.ForeignKeyConstraint(['teamId'], ['teams.id'], ),
    sa.ForeignKeyConstraint(['teamLeaderId'], ['users.id'], ),
    sa.PrimaryKeyConstraint('teamId')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('team_leader')
    op.drop_index(op.f('ix_orders_orderNumber'), table_name='orders')
    op.drop_table('orders')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_need_repair_mans_phone'), table_name='need_repair_mans')
    op.drop_table('need_repair_mans')
    op.drop_table('teams')
    op.drop_index(op.f('ix_schools_schoolName'), table_name='schools')
    op.drop_index(op.f('ix_schools_schoolCode'), table_name='schools')
    op.drop_index(op.f('ix_schools_id'), table_name='schools')
    op.drop_table('schools')
    op.drop_index(op.f('ix_repair_problems_id'), table_name='repair_problems')
    op.drop_table('repair_problems')
    op.drop_index(op.f('ix_phone_verify_codes_phoneNumber'), table_name='phone_verify_codes')
    op.drop_table('phone_verify_codes')
    op.drop_index(op.f('ix_email_verify_codes_email'), table_name='email_verify_codes')
    op.drop_table('email_verify_codes')
    # ### end Alembic commands ###
