"""empty message

Revision ID: 809a83f9dfa0
Revises: 6cc8994556aa
Create Date: 2018-03-22 14:07:42.921734

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '809a83f9dfa0'
down_revision = '6cc8994556aa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('phoneNumber', sa.String(length=12), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'phoneNumber')
    # ### end Alembic commands ###
